### ISSUE TITLE
CuffLinks 2.2.1+ Eigen3 problems to build on Ubuntu 16.04

### ISSUE THREAD

**Issue by malteseunderdog** [cole-trapnell-lab/cufflinks#61]
make for Cufflinks 2.2.1 and Eigen3 fails on the following line:

```
In file included from /usr/include/eigen3/Eigen/Core:297:0,
                 from /usr/include/eigen3/Eigen/Dense:1,
                 from abundances.h:21,
                 from abundances.cpp:16:
/usr/include/eigen3/Eigen/src/Core/DenseCoeffsBase.h: In instantiation of ‘Eigen::DenseCoeffsBase<Derived, 0>::CoeffReturnType Eigen::DenseCoeffsBase<Derived, 0>::coeff(Eigen::Index) const [with Derived = Eigen::PartialReduxExpr<Eigen::Matrix<double, -1, 1>, Eigen::internal::member_sum<double>, 0>; Eigen::DenseCoeffsBase<Derived, 0>::CoeffReturnType = double; Eigen::Index = long int]’:
/usr/include/eigen3/Eigen/src/Core/DenseCoeffsBase.h:181:19:   required from ‘Eigen::DenseCoeffsBase<Derived, 0>::CoeffReturnType Eigen::DenseCoeffsBase<Derived, 0>::operator()(Eigen::Index) const [with Derived = Eigen::PartialReduxExpr<Eigen::Matrix<double, -1, 1>, Eigen::internal::member_sum<double>, 0>; Eigen::DenseCoeffsBase<Derived, 0>::CoeffReturnType = double; Eigen::Index = long int]’
abundances.cpp:3815:28:   required from here
/usr/include/eigen3/Eigen/src/Core/util/StaticAssert.h:119:9: error: ‘THIS_COEFFICIENT_ACCESSOR_TAKING_ONE_ACCESS_IS_ONLY_FOR_EXPRESSIONS_ALLOWING_LINEAR_ACCESS’ is not a member of ‘Eigen::internal::static_assertion<false>’
         if (Eigen::internal::static_assertion<static_cast<bool>(CONDITION)>::MSG) {}
         ^
/usr/include/eigen3/Eigen/src/Core/DenseCoeffsBase.h:141:7: note: in expansion of macro ‘EIGEN_STATIC_ASSERT’
       EIGEN_STATIC_ASSERT(internal::evaluator<Derived>::Flags & LinearAccessBit,
```

**Comment by malteseunderdog** [comment]
The problem is that if you install Eigen3 via sudo apt-get install libeigen3-dev Ubuntu's 16.04 package is incompatible with cufflinks ... workaround - install an older EIgen3 from the EIgen3 website.

**Comment by tillea** [comment]
Hi,

Jakub Wilk found a better workaround for the Debian package:

    https://anonscm.debian.org/cgit/debian-med/cufflinks.git/tree/debian/patches/lib_eigen.patch

While saying so the best workaround is probably using the Debian package maintained by the Debian Med team.

Kind regards

          Andreas.
