### ISSUE TITLE
fails to compile with boost 1.56+

### ISSUE THREAD

**Issue by wookietreiber** [cole-trapnell-lab/cufflinks#3]
I am on an up to date Arch Linux with boost 1.57.0. cufflinks compilation fails at target `abundances.o` with the following errors (this is the output of clang++ which I find ~~nicer~~ visually better than g++):

```
In file included from abundances.cpp:16:
In file included from ./abundances.h:17:
In file included from /usr/bin/../lib64/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../include/c++/4.9.2/vector:60:
In file included from /usr/bin/../lib64/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../include/c++/4.9.2/bits/stl_algobase.h:64:
/usr/bin/../lib64/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../include/c++/4.9.2/bits/stl_pair.h:119:22: error: no matching constructor for initialization of 'boost::shared_ptr<void>'
        : first(__p.first), second(__p.second) { }
                            ^      ~~~~~~~~~~
```

```
In file included from abundances.cpp:16:
In file included from ./abundances.h:17:
In file included from /usr/bin/../lib64/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../include/c++/4.9.2/vector:60:
In file included from /usr/bin/../lib64/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../include/c++/4.9.2/bits/stl_algobase.h:64:
/usr/bin/../lib64/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../include/c++/4.9.2/bits/stl_pair.h:119:22: error: no matching constructor for initialization of 'boost::shared_ptr<void>'
        : first(__p.first), second(__p.second) { }
                            ^      ~~~~~~~~~~
```

I presume errors like these may occur in other places as well.

**Comment by ctrapnell** [comment]
This compilation failure results from a bug in Boost serialization in 1.56+ (https://svn.boost.org/trac/boost/ticket/10488).  Although there appears to be some disagreement about whether this truly is considered a bug, Cufflinks appears to be one of many programs affected by the shared_ptr serialization policy change.  Working around this in Cufflinks looks like it requires that I remove const qualifiers on numerous shared_ptrs, which I'm not willing to do. This will remain open for the time being.  Users should stick to Boost 1.55 and lower.

**Comment by robertramey** [comment]
note this is corrected in the boost master branch and will appear in the next boost release

**Comment by smowton** [comment]
:D Thanks @robertramey

**Comment by ryandesign** [comment]
I tested with boost 1.58.0 beta 1, released March 16, 2015, and the problem remains.

**Comment by nsoranzo** [comment]
Can this be mentioned in http://cole-trapnell-lab.github.io/cufflinks/getting_started/ ? It would save people some time!

**Comment by ryandesign** [comment]
I tested with boost 1.58.0, released April 17, 2015, and the problem remains.

**Comment by ctrapnell** [comment]
Apparently the fix didn't take the first time around.  Looks like we'll have to wait for 1.59 for the official fix in Boost::Serialization.  I will update the getting started page for those who want to build from source.

**Comment by mschubert** [comment]
[1.59 is in beta](http://www.boost.org/users/history/version_1_59_0.html), did anyone try this already?

**Comment by xnox** [comment]
https://github.com/boostorg/serialization/commit/010055816681a003a8090d105ea5ab385bb87bf8.patch is the fix, no?

**Comment by mschubert** [comment]
Just tested on gentoo_prefix with boost=1.59, and it works.

**Comment by ctrapnell** [comment]
Confirmed - I can also build on OS X via macports' boost 1.59.
